### ISSUE TITLE
Investigate Windows CLI credentials file generation

### ISSUE THREAD

**Issue by malandis** [momentohq/momento-cli#157]
A user running Windows 11 installed the CLI. He used the `config` verb to set his auth token and create a default cache. The default cache was created, but the credentials file did not have his auth token in it. On the next invocation of the CLI, the CLI bailed, complaining about a malformed auth token. We confirmed his default cache had been created from the config process.

Later we asked about the state of his .momento folder. The folder and credentials file were there. The credentials file had these contents:
```
[default]
token=
```
Note the absence of the token value.

**Comment by malandis** [comment]
NB: the CLI project uses Linux and MacOS directory separators ("/") in [multiple places](https://github.com/momentohq/momento-cli/blob/main/src/utils/file.rs#L13). Consider using [std::Path](https://doc.rust-lang.org/std/path/index.html) for cross platform path manipulation.

**Comment by kvcache** [comment]
Is this `cmd`, `powershell` or some flavor of `wsl` or `wsl2`? Something else?
`std::Path` is the right tool, but fyi powershell tries reasonably hard to respect `/`.

**Comment by malandis** [comment]
I am unable to reproduce this. I logged in to a fresh Windows 11 install, downloaded the CLI binary, unzipped, then went through the configure process from a CMD prompt. The credentials file was created and contained the token value.
