### ISSUE TITLE
`Default cache` confusion in `configure`

### ISSUE THREAD

**Issue by rlinehan** [momentohq/momento-cli#35]
This might actually be better as two separate issues, but I wasn't quite sure because I think the overarching theme is how exactly should "configure" work for the `default cache`? I also don't think either of these are particularly high priority, just things I noticed when trying out the CLI:

#### 1. When running `momento configure` it asks for `Default Cache`. It doesn't complain if you don't provide anything:

```
$ momento configure
Token [****]: <token>
Default Cache:
Default Ttl Seconds [0]:
```

However, if you then try to do `set` with this default, you get an error:

```
$ momento cache set --key cat --value halla
[2022-01-12T01:39:05Z INFO  momento::commands::cache::cache] setting key: cat into cache:
[2022-01-12T01:39:06Z ERROR momento] panicked at 'Permission denied', src/commands/cache/cache.rs:17:19
```

At the very least I would expect a better error message here than `Permission denied`? Like, if you don't have a default cache set then it prompts that you must use `--name`?

#### 2. I sort of expected that when I set my "default cache" that that cache would be created for me
This means that my initial workflow looks like:

1. run `momento configure` and set my `default cache`
2. remember what I set my default cache to and then create it with `momento cache create`
3. then I can run `momento cache set` and it won't error

It might be a slightly nicer onboarding experience if the tool created my `default cache` for me when I set it up. 

Alternatively, I could see something like maybe you can run pieces of `momento configure` separately - like you start with `momento configure auth` so that all you're setting is your auth token, and you can come back later to set a default cache if you want to?

**Comment by rlinehan** [comment]
> At the very least I would expect a better error message here than `Permission denied`?

I opened an issue in cacheservice for the permission denied part of this https://github.com/momentohq/cacheservice/issues/449.

**Comment by danielamiao** [comment]
bullet 2 above is fixed as of https://github.com/momentohq/momento-cli/pull/54 we now create the default cache during `momento configure`
