### ISSUE TITLE
Fix how `momento configure` interacts with config file

### ISSUE THREAD

**Issue by danielamiao** [momentohq/momento-cli#40]
The config file should:

- Supports default profile with a token, default cache name, and default TTL
- Supported named profiled with a token, optional cache name, and TTL

On command line, support passing in named profile via env var:

```
# use default profile
momento cache get --key

# use named profile
MOMENTO_PROFILE=iad-region momento cache get --key
```

- [x] Add support for momento config file to support multiple profiles (this unblocks an immediate demand to store multiple tokens for multiple regions, including myself). For instance, I want to be able to do momento --profile public-us-east-1 cache list 
https://github.com/momentohq/momento-cli/issues/56

- [x] For now, momento configure supports onboarding new users only, i.e. it only works if you do not have an existing momento config file. This command basically creates the config file and stores a token, cache name, TTL for default named profile.
If a user with an existing momento config file tries running momento configure , it will throw an error and print something like "Existing config file detected, please edit $HOME/.momento/config directly to add or modify profiles".
https://github.com/momentohq/momento-cli/issues/57

- [ ] We will port over "update config without clobbering" functionality from python to Rust, then add support to momento configure to enable editing config via CLI.
https://github.com/momentohq/momento-cli/issues/58

**Comment by danielamiao** [comment]
Should resolve: #37 , #38 , #27 , #34 , #35 , #32 , #36

**Comment by bruuuuuuuce** [comment]
Do we want the user to just manually create their config files for now?

**Comment by danielamiao** [comment]
@bruuuuuuuce yes exactly, but we should provide a template config.toml for them to fill out

**Comment by danielamiao** [comment]
Whoever picks this up next, sync with @cprice404 to discuss the plan before proceeding please

**Comment by poppoerika** [comment]
@gautamomento @bruuuuuuuce @rlinehan @cprice404 

I wrote up my findings for the above questions. Please take a look and let me know if I missed/misunderstood anything!

1. Determine TOML Support and adoption is sufficient for above mentioned criteria
    - Ability for lossless edit
    I'd assume that we're looking for Rust solutions for this. If so, I found that there is [this library](https://docs.rs/toml_edit/latest/toml_edit/) to edit toml files while preserving comments, spaces and relative order or items. With this, it seems that we could tackle #37 as well as #38. It certainly needs to be tested to see if this library fits our needs but it looks somewhat promising to the file-parsing-in-rust noob's eye. 
    - Wide compatibility 
    TOML is widely supported by the following languages: C, C#, C++, Clojure, Dart, Elixir, Erlang, Go, Haskell, Java, Javascript, Lua, Objective-C, Perl, PHP, Python, Ruby, Swift, Scala and [more](https://github.com/toml-lang/toml/wiki).

2. Is AWS Config file format sufficient for our use cases as well?
    AWS CLI directs users to format their `config` files in INI format.
    From their README [Configuration section](https://github.com/aws/aws-cli#configuration):
    <img width="858" alt="image" src="https://user-images.githubusercontent.com/22686260/153513405-d87d984d-a63c-4ae8-8f99-6cec8b74cbc0.png">
    To implement lossless edits of INI files, these are the crates I found: [rust-ini](https://github.com/zonyitoo/rust-ini) and [configparser-rs](https://github.com/QEDK/configparser-rs). 
    Again, these need to be tested to determine if they achieve what we're trying to accomplish.
    Also, INI file compatibility can be found [here](https://en.wikipedia.org/wiki/INI_file#Comparison_of_INI_parsers).
    There are no data types in INI and everything is encoded as a string.
  
3. Are there any other file formats that should be looked at?
    Other popular file formats are YAML and JSON; however I'm not sure if these are particularly better than TOML or INI. YAML can create nested hierarchy, but not sure we need that feature in Momento CLI. JSON cannot include comments. For other advantages/disadvantages are listed in [this blog post](https://octopus.com/blog/state-of-config-file-formats). This blog post also talks about XML and HCL (this is a tool specific language).

**Comment by gautamomento** [comment]
> * I'd assume that we're looking for Rust solutions for this.

Not just Rust we should look at other languages also and see if they allow lossless edits. If down the line, we decide to not continue using Rust then we should be able to migrate. Similarly, not all customers would use Rust to change these files in lossless format. I think we have wide compatibility with TOML going for us - it may also be nice to quickly lookup how easy is lossless editing in those languages.

**Comment by poppoerika** [comment]
Append to an existing file (no overwrite):

- C [opne](https://man7.org/linux/man-pages/man2/open.2.html) with mode `O_APPEND` and [write](https://man7.org/linux/man-pages/man2/write.2.html)
- C++ [open](https://www.cplusplus.com/reference/fstream/ofstream/open/) with mode `app`
- C# [File.AppendText](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.appendtext?view=net-6.0)
- Java [write](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#write(java.nio.file.Path,%20java.lang.Iterable,%20java.nio.charset.Charset,%20java.nio.file.OpenOption...)) with OpenOption `StandardOpenOption.APPEND`
- Python [open](https://docs.python.org/3/library/functions.html#open) with mode `a`
- Golang [OpenFile](https://pkg.go.dev/os#OpenFile) with filemode `os.O_APPEND`
- JavaScript [open](https://nodejs.org/api/fs.html#fspromisesopenpath-flags-mode) with `a` flag

**Comment by rlinehan** [comment]
I think, although @cprice404 might correct me, that we want the ability not just to append to a file. Say I have something like
```
[profile.default]
# default settings for my app because reasons
cache = "foo"
ttl = 15
```

and then I want to change the ttl, and I do something like `momento configure --ttl=60`. In that case I would expect the result to be

```
[profile.default]
# default settings for my app because reasons
cache = "foo"
ttl = 60
```

not

```
[profile.default]
# default settings for my app because reasons
cache = "foo"
ttl = 15
ttl = 60
```

I worry that "append" just means the latter - that it adds the new item where we want to replace but ONLY what we tell it to replace.

**Comment by poppoerika** [comment]
- First, ensure config file support multiple profiles so users can use the CLI to talk to multiple regions if they have multiple tokens.
- Then, ensure momento configure can updates these profiles, maybe momento configure --profile <name>to edit different profiles?
- Ensure momento configure doesn't clobber existing data like comments, or other profiles.

**Comment by poppoerika** [comment]
Rust ini file parser: https://github.com/QEDK/configparser-rs
Python ini file parser: https://docs.python.org/3/library/configparser.html
Java ini file parser: http://ini4j.sourceforge.net/
JavaScript ini file parser: https://github.com/npm/ini
Golang ini file parser: https://github.com/go-ini/ini

**Comment by poppoerika** [comment]
I have been looking into more on how we can achieve the following:
1. Read INI format files so that users can specify a preferred profile
2. Write new INI format files 
3. Update existing INI format files without clobbering existing data if the files already exist

After playing with a few Rust crates, it seems possible to implement 1 and 2 fairly easily. 
However, in order to implement 3, I think we need to convert some of the config writer in AWS CLI to Rust and see if it works.

- https://github.com/aws/aws-cli/blob/45b0063b2d0b245b17a57fd9eebd9fcc87c4426a/awscli/customizations/configure/writer.py#L27
- https://github.com/aws/aws-cli/blob/45b0063b2d0b245b17a57fd9eebd9fcc87c4426a/awscli/customizations/configure/configure.py#L122

It seem that it would take more time to implement this than I originally expected, so wanted to make sure that this approach seems reasonable.
