### ISSUE TITLE
Trim white space from JWT on momento configure

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/momento-cli#49]
When copying and pasting from email its really easy to acciently get some white space infront when pasting JWT when running `momento configure` this results in following error for user.

<img width="1067" alt="Screen Shot 2022-02-07 at 1 56 04 PM" src="https://user-images.githubusercontent.com/5491827/152878963-d5317f40-1dbe-404a-911b-b4d985e7c4d5.png">

For reference I only had single white space in front when pasting into `momento configure` workflow.

<img width="150" alt="Screen Shot 2022-02-07 at 1 57 40 PM" src="https://user-images.githubusercontent.com/5491827/152879017-074b21a8-59bb-49ff-bda0-ea28134b0ab3.png">

**Comment by bruuuuuuuce** [comment]
closed by https://github.com/momentohq/momento-cli/pull/50
