### ISSUE TITLE
Cred and config file permissions should match how aws cli sets them

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/momento-cli#67]
You get terminal prompt asking if your sure ok to remove credential file because we dont give user write access. Also we should probably only give r/w to local user vs other users on system.

<img width="487" alt="Screen Shot 2022-03-14 at 3 04 45 PM" src="https://user-images.githubusercontent.com/5491827/158268892-dd69804a-0687-45c1-8f42-8d6fe2a403a6.png">
<img width="459" alt="Screen Shot 2022-03-14 at 3 05 43 PM" src="https://user-images.githubusercontent.com/5491827/158268898-3ceec74d-4c1f-46e1-8f96-f8652d82ab98.png">

Comparison of aws vs momento
<img width="517" alt="Screen Shot 2022-03-14 at 3 06 41 PM" src="https://user-images.githubusercontent.com/5491827/158268993-1369fd9e-0ebb-4d07-acad-6dbe87b67c3e.png">

**Comment by poppoerika** [comment]
Latest momento-cli file permission
```
-rw-------   1 erikatharp  staff    38 Mar 28 12:35 config
-r--------   1 erikatharp  staff   285 Mar 28 12:35 credentials
```

**Comment by poppoerika** [comment]
Based on the conversation we had w/ @kvcache and @bruuuuuuuce, we'll set `600` for both confidentials/config files.
