### ISSUE TITLE
Dont let user enter empty cache name on configure.

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/momento-cli#68]
Should not just continue configure and then fail creating cache if we dectect user used empty cache name. This is really easy to hit when copying and pasting in a JWT to use if it has a new line on accident at end. Then it fails and no easy way to go back. Should fail upfront.

<img width="758" alt="Screen Shot 2022-03-14 at 3 18 47 PM" src="https://user-images.githubusercontent.com/5491827/158270283-f47a3ade-2f22-407f-a859-e3627bc6d76b.png">

**Comment by danielamiao** [comment]
@eaddingtonwhite I think it's actually better to just have a default cache name (`default-cache`) similar to the TTL prompt, instead of err-ing user out on empty i think
