### ISSUE TITLE
Publish binary to GH artifacts for install on linux distros

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/momento-cli#97]

**Comment by danielamiao** [comment]
https://github.com/stripe/stripe-cli/actions/runs/2067585980 here is an example of Stripe's CLI build action to release across different OS platforms

**Comment by danielamiao** [comment]
To start, we don't need rpm or apt install, probably a simple downloadable binary on Linux will suffice, Stripe examples:

1. Striple releases on github, binary for every platform directly downloadable: https://github.com/stripe/stripe-cli/releases/tag/v1.8.6
2. Stripe Github action example for releases: https://github.com/stripe/stripe-cli/actions/runs/2067585980
